version: "3.7"
services:
  nestjs-backend:
    container_name: nestjs-backend-prod
    build:
      target: production
    ports:
      - ${BACKEND_PORT_2}:${BACKEND_PORT_2}
    environment:
      PORT: ${BACKEND_PORT_2}
    #command: npm run start:prod oder CMD ["node", "dist/main"] -> könnte ich beides auslgagern in YAML
    healthcheck:
      test: curl --fail -s http://localhost:${BACKEND_PORT_2}/backend/ || exit 1
      interval: 500s
      timeout: 5s
      retries: 3
