#------------------------- DEVELOPMENT STAGE -------------------------#
#FROM node:18-alpine AS development
#ENV TZ=Europe/Germany
#WORKDIR /workplace-backend/src/app
#COPY package.json package-lock.json ./
#RUN npm ci --omit=dev
#COPY . .

#RUN npm run build

#------------------------- PRODUCTION STAGE -------------------------#
#FROM node:18-alpine3.14 AS production
#WORKDIR /workplace-backend/src/app
#COPY package*.json ./
#RUN npm ci --only=production
#COPY --from=development /workplace-backend/src/app/dist ./dist
#COPY --chown=node:node . /workplace-backend/src/app
#USER node
#CMD [ "node", "dist/main" ]



###Version 2

###################
# BUILD FOR LOCAL DEVELOPMENT
###################
 
FROM node:18-alpine AS install-dependencies
 
WORKDIR /workplace-backend/src/app
 
COPY --chown=node:node package*.json ./
 
RUN npm ci --omit=dev
 
COPY --chown=node:node . .
 
 
###################
# BUILD FOR PRODUCTION
###################
 
FROM node:18-alpine AS create-build
 
WORKDIR /workplace-backend/src/app
 
COPY --from=install-dependencies /workplace-backend/src/app ./
 
RUN npm run build
 
USER node
 
 
# Running the application:
 
FROM node:18-alpine AS run
 
WORKDIR /workplace-backend/src/app
 
COPY --from=install-dependencies /workplace-backend/src/app/node_modules ./node_modules
COPY --from=create-build /workplace-backend/src/app/dist ./dist
COPY package.json ./
 
CMD ["npm", "run", "start:prod"]

