version: "3.7"
services:
  nestjs-backend:
    build:
      dockerfile: Dockerfile
      context: . 
    volumes:
      - ./nestjs-backend:/workplace-backend/src/app
      - /workplace-backend/src/app/node_modules/
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_URL: ${DATABASE_URL}
   # links:
    #  - mongo
    networks:
      - project_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
     
networks:
  project_network:
    driver: bridge



#depends_on: mongo? geht das noch? 