version: "3.7"
services:
  nestjs-backend:
    build:
      dockerfile: Dockerfile
      context: . 
    volumes:
      - .:/workplace-backend/src/app
      - /workplace-backend/src/app/node_modules/
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_URL: ${DATABASE_URL}
    networks:
      - project_network

networks:
  project_network:
    driver: bridge



#depends_on: mongo? geht das noch? 