version: "3.7"
services:
  nestjs-backend:
    container_name: nestjs-backend-debug
    build:
      target: development
    ports:
      - "${BACKEND_PORT_1}:${BACKEND_PORT_1}"
      - "9229:9229"
    environment:
        PORT: ${BACKEND_PORT_1} # Das ist doch unnötig, oder?
    command: npm run start:inspect
    healthcheck:
      test: curl --fail -s http://localhost:${BACKEND_PORT_1}/backend/ || exit 1
      interval: 500s
      timeout: 5s
      retries: 3 #healtcheck? Das ist nich implemetiert
