version: "3.7"
services:
  nestjs-backend:
    container_name: nestjs-backend-dev
    build:
      target: development
    ports:
      - "${BACKEND_PORT_1}:${BACKEND_PORT_1}" # sind die Anführungszeichen hier notwendig?
    environment:
      PORT: ${BACKEND_PORT_1}
    command: npm run start:dev
    healthcheck:
      test: curl --fail -s http://localhost:${BACKEND_PORT_1}/backend/ || exit 1
      interval: 500s
      timeout: 5s
      retries: 3

