version: '3.7'
services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9000'
      - '9443:9443' 
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    command:
      - '--admin-password-file=/run/secrets/portainer_admin_password'
      - '--no-analytics'
    secrets:
      - portainer_admin_password
    networks:
      - project_network

volumes:
  portainer-data:
    driver: local

networks:
  project_network:
    driver: bridge

secrets:
  portainer_admin_password:
    file: ./secrets/portainer-admin-password.txt