version: "3.7"
services:
  backend:
    build:
      target: development
    ports:
      - ${BACKEND_PORT_1}:${BACKEND_PORT_1}
    env_file:
      - .env
    environment:
      PORT: ${BACKEND_PORT_1}
      DB_URL: ${DATABASE_URL}
      MONGO_HOST: ${MONGO_HOST}
    command: npm run start:dev
    healthcheck:
      test: curl --fail -s http://localhost:${BACKEND_PORT_1}/backend/ || exit 1
      interval: 500s
      timeout: 5s
      retries: 3